#!/usr/bin/env python3
"""
Mock pass-cli for proton-relay tests.

Output shapes: fixtures were generated by pass-cli 2.4.1's own pass-domain serde models.
Error strings: copied from pass-cli 2.4.1 source / observed from the real binary.

Session race model: Proton refresh tokens rotate, so two pass-cli processes on one
session at once can clobber each other. Any overlapping invocation is recorded as an
overlap, invalidates the session, and fails with the no-session error.

Control files in $MOCK_DIR:
  session       exists => logged in
  expire_next   next `item view` expires the session first (then the flag is removed)
  login_fail    `login` fails
  calls.jsonl   one JSON line per invocation (argv + relevant env)
  overlaps      count of detected concurrent invocations
"""
import json
import os
import sys
import time
from pathlib import Path

M = Path(os.environ["MOCK_DIR"])
FIXTURES = Path(os.environ["MOCK_FIXTURES"])
VAULT = os.environ.get("MOCK_VAULT", "Homelab")
LATENCY = float(os.environ.get("MOCK_LATENCY", "0"))
HANG_TITLE = os.environ.get("MOCK_HANG_TITLE")
GARBAGE_TITLE = os.environ.get("MOCK_GARBAGE_TITLE")

ANSI_ERR = "\x1b[2m2026-09-23T10:27:07.354009Z\x1b[0m \x1b[31mERROR\x1b[0m \x1b[2mpass-cli/src/main.rs\x1b[0m\x1b[2m:\x1b[0m\x1b[2m334:\x1b[0m Command is not logout there is no session"
BACKTRACE = "\nStack backtrace:\n   0: anyhow::error::<impl anyhow::Error>::msg\n   1: pass_cli::run::{{closure}}\n"


def fail(msg: str, code: int = 1):
    bt = BACKTRACE if os.environ.get("RUST_BACKTRACE", "1") != "0" else ""
    sys.stderr.write(f"Error: {msg}\n{bt}")
    sys.exit(code)


def no_session():
    sys.stderr.write(ANSI_ERR + "\n")
    fail("This operation requires an authenticated client")


def record(argv):
    entry = {
        "argv": argv,
        "t": time.time(),
        "key_provider": os.environ.get("PROTON_PASS_KEY_PROVIDER"),
        "backtrace": os.environ.get("RUST_BACKTRACE"),
        "reason": os.environ.get("PROTON_PASS_AGENT_REASON"),
        "has_pat": bool(os.environ.get("PROTON_PASS_PERSONAL_ACCESS_TOKEN")),
    }
    with open(M / "calls.jsonl", "a") as f:
        f.write(json.dumps(entry) + "\n")


def bump(name: str):
    p = M / name
    # best-effort counter; overlaps are rare enough that a lost increment doesn't matter for >0 asserts
    n = int(p.read_text() or 0) if p.exists() else 0
    p.write_text(str(n + 1))


def logged_in() -> bool:
    return (M / "session").exists()


def arg_value(argv, flag):
    for a in argv:
        if a.startswith(flag + "="):
            return a.split("=", 1)[1]
    if flag in argv:
        i = argv.index(flag)
        return argv[i + 1] if i + 1 < len(argv) else None
    return None


def item_view(argv):
    uri = next((a for a in argv[2:] if a.startswith("pass://")), None)
    if uri:  # URI form (used by the ORIGINAL relay)
        parts = uri[len("pass://"):].split("/")
        vault, title = parts[0], parts[1] if len(parts) > 1 else ""
        vault_err = f"Error retrieving item\n\nCaused by:\n    0: Error finding item by name\n    1: Error finding vault by name\n    2: Could not find vault {vault}"
        item_err = f"Error retrieving item\n\nCaused by:\n    0: Error finding item by name\n    1: Could not find item with name {title}"
    else:    # flag form (used by the NEW relay)
        vault, title = arg_value(argv, "--vault-name"), arg_value(argv, "--item-title")
        vault_err = f"Error finding vault [{vault}]: Could not find vault {vault}"
        item_err = f"No item found with title: {title}"

    if not logged_in():
        no_session()
    if (M / "expire_next").exists():
        (M / "expire_next").unlink()
        (M / "session").unlink(missing_ok=True)
        no_session()
    if title == HANG_TITLE:
        (M / "inflight").rmdir()  # a SIGKILLed process must not poison later calls
        time.sleep(3600)
    if vault != VAULT:
        fail(vault_err)
    if title == GARBAGE_TITLE:
        print("{not json")
        return
    fx = FIXTURES / f"{title}.json"
    if not fx.is_file():
        fail(item_err)
    sys.stdout.write(fx.read_text())  # fixture already ends with println!'s newline


def main():
    argv = sys.argv[1:]
    record(argv)

    # Concurrency detection: an atomic mkdir marks "a pass-cli process is using the session".
    marker = M / "inflight"
    try:
        marker.mkdir()
    except FileExistsError:
        bump("overlaps")
        (M / "session").unlink(missing_ok=True)   # rotated refresh token clobbered
        no_session()
    try:
        if LATENCY:
            time.sleep(LATENCY)
        cmd = argv[:2] if argv[:1] == ["item"] else argv[:1]
        if cmd == ["logout"]:
            (M / "session").unlink(missing_ok=True)
            print("Executing force logout\nSuccessfully performed force logout")
        elif cmd == ["login"]:
            if not os.environ.get("PROTON_PASS_PERSONAL_ACCESS_TOKEN"):
                fail("web login is not possible in this environment")
            if (M / "login_fail").exists():
                fail("Error in personal access token login flow\n\nCaused by:\n    0: Error creating personal access token session")
            (M / "session").write_text("1")
            print("Logged in as noreply@nebulahvelvet.no")
        elif cmd == ["info"]:
            if not logged_in():
                no_session()
            print("Session: valid")
        elif cmd == ["item", "view"]:
            item_view(argv)
        else:
            fail(f"mock: unsupported command {argv}", 2)
    finally:
        try:
            marker.rmdir()
        except FileNotFoundError:
            pass


if __name__ == "__main__":
    main()
